apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts
  labels:
    app: ts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts
  template:
    metadata:
      labels:
        app: ts
    spec:
      containers:
        - name: ts
          image: abidurrehman/txt2speech-ui
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ts-service
spec:
  selector:
    app: ts
  ports:
    - protocol: TCP
      port: 3000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ts-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: ts.holidaynumbers.co.uk
      http:
        paths:
          - path: /
            backend:
              serviceName: ts-service
              servicePort: 3000
  tls:
    - hosts:
        - ts.holidaynumbers.co.uk
      secretName: ts-holidaynumbers-co-uk-tls